framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
        routing:
            # Route your messages to the transports
